DEVICE_ID = "mastr_r2a"
FIRMWARE_VERSION = "2.0.0-pi"

LED_SPI_BUS = 0
LED_SPI_DEVICE = 0
LED_DATA_PIN = 10
LED_CLOCK_PIN = 11
LED_COUNT = 72
LEDS_PER_ENCODER = 72
ACTIVE_LEDS_PER_ENCODER = 24
LED_BRIGHTNESS = 8
LED_UPDATE_RATE_MS = 16
LED_COLOR_ORDER = 'bgr'

TEST_ENCODER_PIN_A = 17
TEST_ENCODER_PIN_B = 27
TEST_ENCODER_PIN_BTN = 22

PCF_I2C_BUS = 1
PCF_I2C_SPEED = 400000
PCF_BASE_ADDRESS = 0x20
PCF_NUM_ENCODERS = 8
PCF_ENCODER_PIN_A = 0
PCF_ENCODER_PIN_B = 1
PCF_ENCODER_PIN_BTN = 2
PCF_POLLING_RATE_HZ = 100

PCF_INT_PINS = {
    0: 5,
    1: 6,
    2: 13,
    3: 19,
    4: 26,
    5: 16,
    6: 20,
    7: 21,
}

WEBSOCKET_IP = "192.168.4.1"
WEBSOCKET_PORT = 8765
HEARTBEAT_INTERVAL_MS = 500

ENABLE_TEST_ENCODER = True
ENABLE_PCF_ENCODERS = False
USE_PCF_INTERRUPTS = False

MSG_TYPE_STARTUP = "startup"
MSG_TYPE_HEARTBEAT = "heartbeat"
MSG_TYPE_STATUS = "status"
MSG_TYPE_ENCODER = "encoder"
MSG_TYPE_BUTTON_PRESS = "button_press"
MSG_TYPE_LED_UPDATE = "led_update"
MSG_TYPE_SYSTEM_COMMAND = "system_command"
MSG_TYPE_ERROR = "error"
MSG_TYPE_BRIDGE_STATUS = "bridge_status"
MSG_TYPE_PARAMETER_STRUCTURE_SYNC = "parameter_structure_sync"
MSG_TYPE_PARAMETER_VALUE_SYNC = "parameter_value_sync"
MSG_TYPE_PARAMETER_COLOR_SYNC = "parameter_color_sync"
MSG_TYPE_BRIDGE_COMMAND = "bridge_command"

